# Makefile

TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/../../../../generated/SendReceiveSynchronizer.sv
TOPLEVEL = SendReceiveSynchronizer
MODULE = test_SendReceiveSynchronizer

include $(shell cocotb-config --makefiles)/Makefile.sim
